In [1]:
import numpy as np
import pandas as pd

In [29]:
data = pd.read_excel('data/Online Retail.xlsx')
data.shape

(541909, 8)

In [30]:
data.to_csv('data/Online Retail.csv')

In [31]:
# data = pd.ead_csv('data/Online Retail.csv')
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [32]:
data.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [33]:
dataFraction = 0.1
data = data.sample(frac = dataFraction, random_state = 42).reset_index(drop = True)

In [35]:
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,555200,71459,HANGING JAM JAR T-LIGHT HOLDER,24,2011-06-01 12:05:00,0.85,17315.0,United Kingdom
1,554974,21128,GOLD FISHING GNOME,4,2011-05-27 17:14:00,6.95,14031.0,United Kingdom
2,550972,21086,SET/6 RED SPOTTY PAPER CUPS,4,2011-04-21 17:05:00,0.65,14031.0,United Kingdom
3,576652,22812,PACK 3 BOXES CHRISTMAS PANETTONE,3,2011-11-16 10:39:00,1.95,17198.0,United Kingdom
4,546157,22180,RETROSPOT LAMP,2,2011-03-10 08:40:00,9.95,13502.0,United Kingdom

In [36]:
data.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
54186,581433,22960,JAM MAKING SET WITH JARS,6,2011-12-08 15:54:00,4.25,14911.0,EIRE
54187,551993,85132C,CHARLIE AND LOLA FIGURES TINS,4,2011-05-05 15:39:00,1.95,14697.0,United Kingdom
54188,C559253,22326,ROUND SNACK BOXES SET OF4 WOODLAND,-1,2011-07-07 11:44:00,2.95,12472.0,Germany
54189,559491,21078,SET/20 STRAWBERRY PAPER NAPKINS,1,2011-07-08 13:53:00,2.46,NaN,United Kingdom
54190,548992,21452,TOADSTOOL MONEY BOX,12,2011-04-05 13:52:00,2.95,13089.0,United Kingdom

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54191 entries, 0 to 54190
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    54191 non-null  object
 1   StockCode    54191 non-null  object
 2   Description  54042 non-null  object
 3   Quantity     54191 non-null  int64
 4   InvoiceDate  54191 non-null  datetime64[ns]
 5   UnitPrice    54191 non-null  float64
 6   CustomerID   40551 non-null  float64
 7   Country      54191 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 3.3+ MB

In [38]:
data.describe()

           Quantity                    InvoiceDate     UnitPrice    CustomerID
count  54191.000000                          54191  54191.000000  40551.000000
mean      10.638962  2011-07-04 03:02:48.858297600      4.667784  15279.710167
min    -2472.000000            2010-12-01 08:26:00      0.000000  12346.000000
25%        1.000000            2011-03-28 11:35:00      1.250000  13950.500000
50%        3.000000            2011-07-19 11:03:00      2.080000  15122.000000
75%       10.000000            2011-10-18 17:05:00      4.130000  16791.000000
max    74215.000000            2011-12-09 12:50:00  13541.330000  18287.000000
std      321.689757                            NaN     88.434068   1715.070628

In [43]:
# Drop rows where the Description is missing
# as null description means we cant conclude anything for this product
data.dropna(subset=['Description'], inplace = True)

In [45]:
data['Description'].isnull().sum()

np.int64(0)

In [48]:
num_duplicates = data.duplicated().sum()
print(f"Found {num_duplicates} fully duplicated rows.")

Found 62 fully duplicated rows.

In [51]:
# Remove duplicates, keeping the first instance
data.drop_duplicates(inplace=True)
print(f"Dataframe size after removing duplicates: {len(data)} rows.")

Dataframe size after removing duplicates: 53980 rows.

In [55]:
# Filter: Keep only transactions where Quantity is positive (i.e., sales, not returns)
df = data[data['Quantity'] > 0]

# Filter: Keep only transactions where UnitPrice is positive (i.e., not free or an error)
df = df[df['UnitPrice'] > 0]
print(f"Dataframe size after filtering: {len(df)} rows.")

Dataframe size after filtering: 52933 rows.

In [57]:
# Cleaning Text Columns
# Clean Description and Country columns
df['Description'] = df['Description'].str.strip()
df['Country'] = df['Country'].str.strip()

# Handle specific country name inconsistencies
# EIRE is a common inconsistency in this dataset for Ireland
df['Country'].replace('EIRE', 'Ireland', inplace=True)
print("Text columns cleaned and standardized.")

Text columns cleaned and standardized.

C:\Users\Amritansu Aditya\AppData\Local\Temp\ipykernel_17464\2717411717.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Country'].replace('EIRE', 'Ireland', inplace=True)

In [58]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [62]:
top_countries = df.groupby('Country')['Revenue'].sum().sort_values(ascending=False).head(10)
print(top_countries)

Country
United Kingdom    941268.661
Netherlands        27435.830
Ireland            26066.000
France             23645.330
Germany            22389.510
Australia          12429.990
Spain               5600.900
Switzerland         5483.890
Hong Kong           3597.850
Belgium             3593.510
Name: Revenue, dtype: float64

In [64]:
## top products by quantity
df.groupby('Description')['Quantity'].sum().sort_values(ascending= False).head(10)

Description
MEDIUM CERAMIC TOP STORAGE JAR       74698
WORLD WAR 2 GLIDERS ASSTD DESIGNS     9419
GIN + TONIC DIET METAL SIGN           5016
ASSORTED COLOURS SILK FAN             4684
JUMBO BAG RED RETROSPOT               4671
PACK OF 72 RETROSPOT CAKE CASES       3561
MINI PAINT SET VINTAGE                3285
ASSORTED COLOUR BIRD ORNAMENT         2783
BROCADE RING PURSE                    2525
POPCORN HOLDER                        2508
Name: Quantity, dtype: int64

In [66]:
# Top 10 Revenue Drivers (The True Money-Makers)
df.groupby('Description')['Revenue'].sum().sort_values(ascending=False).head(10)

Description
MEDIUM CERAMIC TOP STORAGE JAR    77785.74
DOTCOM POSTAGE                    18456.13
REGENCY CAKESTAND 3 TIER          15093.38
AMAZON FEE                        13541.33
PARTY BUNTING                      9491.60
GIN + TONIC DIET METAL SIGN        9480.51
JUMBO BAG RED RETROSPOT            8996.65
Manual                             8966.96
CHILLI LIGHTS                      8395.20
POSTAGE                            7194.51
Name: Revenue, dtype: float64

In [68]:
print("\n — — Time Series Feature Extraction — -")

# Extract Year, Month, DayName, and Hour from the InvoiceDate column
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['DayName'] = df['InvoiceDate'].dt.day_name()
df['Hour'] = df['InvoiceDate'].dt.hour
print("New time features added: Year, Month, DayName, Hour.")
print(df[['InvoiceDate', 'Year', 'Month', 'DayName', 'Hour']].head())

 — — Time Series Feature Extraction — -
New time features added: Year, Month, DayName, Hour.
          InvoiceDate  Year  Month    DayName  Hour
0 2011-06-01 12:05:00  2011      6  Wednesday    12
1 2011-05-27 17:14:00  2011      5     Friday    17
2 2011-04-21 17:05:00  2011      4   Thursday    17
3 2011-11-16 10:39:00  2011     11  Wednesday    10
4 2011-03-10 08:40:00  2011      3   Thursday     8

In [69]:
print("\n — — Insight 4: Sales Trends by Month (Seasonality) — -")
# Group by month and sum the revenue
monthly_revenue = df.groupby('Month')['Revenue'].sum().sort_values(ascending=False)
# Print the results, which should show the seasonal peaks
print(monthly_revenue)

 — — Insight 4: Sales Trends by Month (Seasonality) — -
Month
11    143576.360
1     142013.420
12    133178.980
10    119533.540
9     103929.420
3      72968.270
8      71302.890
5      70424.510
6      68722.520
7      68713.831
4      51882.010
2      50178.730
Name: Revenue, dtype: float64

In [70]:
# 1. Sales by Day of Week
daily_revenue = df.groupby('DayName')['Revenue'].sum()
print("\n — — Revenue by Day of Week — -")
print(daily_revenue)

 — — Revenue by Day of Week — -
DayName
Friday       163861.320
Monday       171026.230
Sunday        83125.890
Thursday     219342.980
Tuesday      282796.741
Wednesday    176271.320
Name: Revenue, dtype: float64

In [72]:
# 2. Sales by Hour of Day
hourly_revenue = df.groupby('Hour')['Revenue'].sum().sort_index()
print("\n — — Revenue by Hour of Day — -")
print(hourly_revenue)

 — — Revenue by Hour of Day — -
Hour
7       2830.910
8      26597.800
9      76768.750
10    209809.971
11    115233.600
12    142474.460
13    130348.290
14    119241.520
15    145178.980
16     70620.550
17     36148.030
18     14022.790
19      4397.130
20      2751.700
Name: Revenue, dtype: float64